server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        # CORS handling
        if ($http_origin ~* (http://localhost:8080|http://127.0.0.1:8080)) {
            add_header 'Access-Control-Allow-Origin' "$http_origin" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        }

        # Handle preflight OPTIONS requests
        if ($request_method = OPTIONS) {
            add_header 'Content-Length' 0;
            add_header 'Content-Type' 'text/plain';
            return 204;
        }

        # Basic HTTP Auth
        auth_basic "Restricted";
		auth_basic_user_file /etc/nginx/.htpasswd;

        try_files $uri $uri/ =404;
    }
}
